name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - ambertools=22.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - bleach=4.1.0
  - blosc=1.21.1
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - conda=4.14.0
  - conda-package-handling=1.8.1
  - cryptography=37.0.1
  - curl=7.83.1
  - cython=0.29.32
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.4
  - fftw=3.3.10
  - fontconfig=2.13.1
  - fonttools=4.36.0
  - freetype=2.12.1
  - gawk=5.1.0
  - gettext=0.21.0
  - glib=2.69.1
  - greenlet=1.1.2
  - gsl=2.6
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=68.2
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_resources=5.2.0
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - khronos-opencl-icd-loader=2022.05.18
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.83.1
  - libcxx=14.0.6
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=11.2.0
  - libhwloc=1.11.13
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libpq=13.5
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.10
  - libzip=1.9.2
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.2
  - mdtraj=1.9.7
  - mistune=0.8.4
  - munkres=1.1.4
  - mysql-common=8.0.30
  - mysql-libs=8.0.30
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf-fortran=4.5.4
  - notebook=6.4.11
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.3
  - ocl_icd_wrapper_apple=1.0.0
  - openff-forcefields=2.0.0
  - openff-interchange=0.1.4
  - openff-interchange-base=0.1.4
  - openff-toolkit=0.10.6
  - openff-toolkit-base=0.10.6
  - openff-units=0.1.7
  - openff-utilities=0.1.5
  - openjpeg=2.5.0
  - openmm=7.7.0
  - openssl=1.1.1q
  - packaging=21.3
  - packmol=20.010
  - pandocfilters=1.5.0
  - panedr=0.5.2
  - parmed=3.4.3
  - parso=0.8.3
  - pbr=5.10.0
  - pcre=8.45
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pint=0.19.2
  - pixman=0.40.0
  - plumed=2.7.1
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycairo=1.21.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pydantic=1.9.2
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyqt=5.12.3
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.8.5
  - python-constraint=1.4.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python.app=2
  - python_abi=3.8
  - qt=5.12.9
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - rdkit=2022.03.5
  - readline=8.1.2
  - reportlab=3.5.68
  - requests=2.27.1
  - ruamel_yaml=0.15.100
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=4.19.8
  - six=1.16.0
  - smirnoff99frosst=1.1.0
  - snappy=1.1.9
  - soupsieve=2.3.1
  - sqlalchemy=1.4.40
  - sqlite=3.38.3
  - stack_data=0.2.0
  - terminado=0.13.1
  - testpath=0.6.0
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.1
  - tqdm=4.64.0
  - typing_extensions=4.1.1
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xdrfile=1.1.4
  - xmltodict=0.13.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxt=1.2.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==0.15.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - amberlite==22.0
    - amberutils==21.0
    - async-timeout==5.0.1
    - cachetools==4.2.4
    - clang==5.0
    - comm==0.2.2
    - contourpy==1.1.1
    - cycler==0.10.0
    - debugpy==1.8.14
    - flatbuffers==1.12
    - frozenlist==1.5.0
    - fsspec==2025.3.0
    - gast==0.4.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - gromacs==0.0.0
    - gromacswrapper==0.8.1
    - grpcio==1.47.0
    - h5py==3.1.0
    - ipykernel==6.29.5
    - ipympl==0.9.3
    - joblib==1.0.1
    - jupyter-core==5.8.1
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.7
    - matplotlib==3.4.3
    - mmpbsa-py==16.0
    - multidict==6.1.0
    - nbstripout==0.6.1
    - networkx==2.3
    - numkit==1.2.1
    - numpy==1.19.5
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - packmol-memgen==1.2.3rc0
    - pandas==1.4.3
    - patsy==0.5.6
    - pdb4amber==22.0
    - pillow==9.1.1
    - pip==22.1.2
    - platformdirs==4.3.6
    - plotly==5.9.0
    - propcache==0.2.0
    - protobuf==3.19.4
    - psutil==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - python-graphviz==0.20.3
    - python2==1.2
    - pytraj==2.0.6
    - pytrr==0.4.1
    - pytz==2022.1
    - pyzmq==27.0.0
    - rdkit-pypi==2022.9.5
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sander==22.0
    - schemdraw==0.17
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - seaborn==0.13.2
    - sklearn==0.0
    - statsmodels==0.14.1
    - tenacity==8.0.1
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.6.5
    - tensorflow-estimator==2.6.0
    - termcolor==1.1.0
    - threadpoolctl==2.2.0
    - torch==1.11.0
    - torch-geometric==2.6.1
    - torchaudio==0.11.0
    - torchvision==0.12.0
    - traitlets==5.14.3
    - typing-extensions==3.10.0.2
    - werkzeug==2.1.2
    - wrapt==1.12.1
    - yarl==1.15.2
prefix: /Users/bdneff/conda
